name: flutter_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  logger: ^2.6.1
  result_dart: ^2.1.1

dev_dependencies:
  bloc_lint: ^0.3.1
  build_runner: ^2.7.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/places.json
